[package]
name = "fibonacci-sudoku"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2_proofs = { version = "0.3.0", features = ["dev-graph"] }
rand_core = "0.6.4"
pasta_curves = "0.5.1"
plotters = "0.3.0"

[features] 
dev-graph = []
